rm -rf lib
rm -rf libacpibin
rm -rf libapicbin
rm -rf libatabin
rm -rf libdebugbin
rm -rf libdelegatebin
rm -rf libdevmgrbin
rm -rf libdmgctrlbin
rm -rf libexebin
rm -rf libfsbin
rm -rf libinitrdbin
rm -rf libkeyboardbin
rm -rf libmembin
rm -rf libmmiobin
rm -rf libmodulebin
rm -rf libmousebin
rm -rf libmultibootbin
rm -rf libnmibin
rm -rf libpcibin
rm -rf libpicbin
rm -rf libportsbin
rm -rf libpowerbin
rm -rf libprocbin
rm -rf libregbin
rm -rf librtcbin
rm -rf libserialbin
rm -rf libsoundbin
rm -rf libssebin
rm -rf libsspbin
rm -rf libtimerbin
rm -rf libvgabin
rm -rf posixbin
rm -rf SlylockOS.iso
rm -rf sys
rm -rf tmp
rm -rf env
rm -rf dev
rm -rf initrd.img
rm -rf kernel.bin
rm -rf kernel.sym
rm -rf bin
rm -rf iso